### ISSUE TITLE
When does the new version with jetpack global update get pushed to CRAN?

### ISSUE THREAD

**Issue by jasikpark** [ankane/jetpack#11]
I'm not sure where to annoy you properly with questions, but this seems like a good place... 

Is there a schedule or something for when the release w/ `jetpack global update` gets created? Not to rush or bother you or anything, but it'd be nice to know...

**Comment by jasikpark** [comment]
Thanks!


--  
Caleb Jasik  
calebjasik@jasik.xyz(mailto:calebjasik@jasik.xyz)
https://jasik.xyz
281.614.9841(tel:281.614.9841)

**Comment by ankane** [comment]
👍
