### ISSUE TITLE
jetpack add <package N> re-adds packages 1..N-1

### ISSUE THREAD

**Issue by stepds** [ankane/jetpack#14]
Hi,

linux jetpack 0.4.0, when I added four packages with four distinct `jetpack add` command lines, each line re-added the packages that were added before itself (downloaded and recompiled each).  Specifically
```
jetpack init
jetpack add enc@0.2.0 # downloads, compiles and installs enc
jetpack getopt@1.20.2 # downloads, compiles, installs enc; downloads and installs getopt
jetpack add here@0.1 # d/l / comp / install enc, getopt, here
jetpack add optparse@1.6.0 # d/l / comp / install enc, getopt, here optparse
```
Note that optparse doesn't depend on here, which doesn't depend on getopt...
I would think that all the extra downloading and compiling is unnecessary and unintentional. Can it be avoided or disabled?

Thank you

**Comment by ankane** [comment]
Thanks for the detailed instructions @stepds 👍 Fixed on master.
