### ISSUE TITLE
Error after running jetpack::init(), cannot be loaded

### ISSUE THREAD

**Issue by tblazina** [ankane/jetpack#15]
Upon running `jetpack::init()` everything seems to be working, but I initially got these error and warning message and keep getting them any time I execute any `jetpack::` commands:

```
Error in unloadNamespace(pkgName) : 
  namespace ‘remotes’ is imported by ‘devtools’ so cannot be unloaded
In addition: Warning message:
‘remotes’ namespace cannot be unloaded:
  namespace ‘remotes’ is imported by ‘devtools’ so cannot be unloaded 
```

**Comment by ankane** [comment]
Hey @tblazina, can you provide more info about your installation - specifically the OS version and R version? Also, does the command execute successfully, or does it stop with the error?

**Comment by tblazina** [comment]
Sorry about that, OS is Windows 10 Pro version 1803 OS build 17134.523. R version is 3.5.2.

Just testing it again now by installing and removing a package this error doesn't seem to be happening again. Sorry can't reproduce so will close!

**Comment by ankane** [comment]
Was able to reproduce with:

```r
jetpack::init()
jetpack::add("futile.logger", remote="zatonovo/futile.logger")
jetpack::update("futile.logger")
```

Unfortunately, it looks like the error is happening inside Packrat and couldn't find a way to suppress it, so added a message when an error is detected.
