### ISSUE TITLE
How to use latest changes in remote repo

### ISSUE THREAD

**Issue by tblazina** [ankane/jetpack#16]
I am wondering if there is a way to have jetpack use the latest changes in a specific repo. I know you can use `jetpack::add("somepackage", remote="someauthor/somepackage")` but this seems to be using the latest release. 

For example, `futile.logger` (https://github.com/zatonovo/futile.logger) is on release v.1.4.3 and indeed when I use `jetpack::add("futile.logger", remote="zatonovo/futile.logger")` this version is installed and added to the `DESCRIPTION` and `packrat.lock` files, however the repo has changes which they haven't created a release for yet and I am wondering if it is possible to specify this using `jetpack`?  

Thanks a lot for the great package btw!

**Comment by ankane** [comment]
Hey @tblazina, you can use `jetpack::update("futile.logger")` for this.

**Comment by tblazina** [comment]
Thanks @ankane, after I run `jetpack::update("futile.logger")` it seems to still be using the latest release of `futile.logger` and doesn't include all the code (e.g. I'm trying to use their `appender.file2()` function). Jetpack gives the message after the update:  `Updated futile.logger to 1.4.3 (was 1.4.3)`.

**Comment by ankane** [comment]
Does your `packrat.lock` have GitHub as the source for futile.logger, as well as the latest SHA? The version on GitHub is [1.4.3](https://github.com/zatonovo/futile.logger/blob/d96c47cd96b0876a54a0617232c277ddba02ec86/DESCRIPTION#L4), so the update message will still say that.

**Comment by ankane** [comment]
Closing due to no response
