### ISSUE TITLE
Can't install from a github PR branch

### ISSUE THREAD

**Issue by MilesMcBain** [ankane/jetpack#17]
I thought I might use `jetpack` to test a PR locally without interfering with my main library version. However this didn't work even though I was able to do it with `remotes::install_github()`.

Specifically this command failed:
```r
>jetpack::add("dplyr", remotes = "tidyverse/dplyr@4183/mutate_at_lambda")
Error: HTTP error 422.
  No commit found for SHA: mutate_at_lambda

  Rate limit remaining: 24/60
  Rate limit reset at: 2019-03-02 10:54:20 UTC

  
Error in unloadNamespace(pkgName) : 
  namespace ‘remotes’ is imported by ‘devtools’ so cannot be unloaded

```
While this one succeeded:

```
remotes::install_github("tidyverse/dplyr@4183/mutate_at_lambda")
```

Here is the PR in question: https://github.com/tidyverse/dplyr/pull/4217

**Comment by ankane** [comment]
Hi @MilesMcBain, thanks for reporting 👍 From the error message, it looks it's getting the wrong branch name (missing `4183/` prefix). I'd confirm there isn't another entry in your DESCRIPTION file under `Remotes:` with a different branch. If not, a few follow up questions:

1. What version of Jetpack and remotes are you on?
2. What OS and version of R are you on?
3. Do you get the same error if you create a fresh directory, run `jetpack::init()`, create a DESCRIPTION file with:

```
Package: app
Remotes:
    tidyverse/dplyr@4183/mutate_at_lambda
Imports:
    dplyr
```

And run:

```r
packrat::extlib("remotes")
remotes::install_deps(".", upgrade=FALSE)
```

**Comment by ankane** [comment]
Closing due to no response
