### ISSUE TITLE
Issues with BioConductor packages

### ISSUE THREAD

**Issue by rprops** [ankane/jetpack#18]
Dear,

I've been trying to get jetpack to work for my repo. But I'm running into some issues with Bioconductor packages as dependencies.

I ran:

```
jetpack::init()
jetpack::add("Phenoflow", remote="CMET-UGent/Phenoflow_package")
```
But got the following warning:
```
Installing BiocGenerics (0.32.0) ... 
FAILED
Error: Failed to retrieve package sources for BiocGenerics 0.32.0 from CRAN (internet connectivity issue?)
```
I've tried the suggested solution on packrat, but to no avail. (https://github.com/rstudio/packrat/issues/507)

```
jetpack::init()
options(repos=structure(BiocManager::repositories()))
jetpack::add("Phenoflow", remote="CMET-UGent/Phenoflow_package")
```
Any suggestions?

Thank you!

Ruben

**Comment by ankane** [comment]
Hey @rprops, can you give the `bioconductor2` branch a shot?

```r
remotes::install_github("ankane/jetpack@bioconductor2")
```

Then restart your R session and do:

```r
jetpack::add(c("BiocManager", "BiocGenerics"))
```

**Comment by ankane** [comment]
On 2nd thought, not really happy with that approach. Instead, try updating the `Repos:` line in your `packrat.lock` manually to something like this:

```txt
Repos: CRAN=https://cloud.r-project.org/,
    BioCsoft=https://bioconductor.org/packages/3.10/bioc,
    BioCann=https://bioconductor.org/packages/3.10/data/annotation,
    BioCexp=https://bioconductor.org/packages/3.10/data/experiment,
    BioCworkflows=https://bioconductor.org/packages/3.10/workflows
```

(no need to use the branch above)

**Comment by rprops** [comment]
Already tried solution #1 and seems to have worked - I'll check out solution #2 later. Thanks for the quick fix @ankane !

**Comment by ankane** [comment]
Updated the instructions here: https://github.com/ankane/jetpack#bioconductor
