### ISSUE TITLE
[Request] Specify library

### ISSUE THREAD

**Issue by artemklevtsov** [ankane/jetpack#2]
Hi,

Thank you for the interesting package.

It would be nice add possibility to specify packages directory. I want to hold my packages in the project directory and track it with GIT.

**Comment by ankane** [comment]
Hey @artemklevtsov, I created a `vendor_src` branch with this ability. It uses the `packages` directory if one exists in the root of your project (although a less common name might be better).

**Comment by ankane** [comment]
Moved to #1
