### ISSUE TITLE
improve check for non-interactive sessions

### ISSUE THREAD

**Issue by kevinushey** [ankane/jetpack#24]
In here:

https://github.com/ankane/jetpack/blob/3d38469dd97c6c785dc426f4379fd29513c19667/R/helpers.R#L317-L325

A test (for example, in `R CMD check`) might be run non-interactively, but the tests currently assume that tests are run interactively.

https://github.com/ankane/jetpack/blob/3d38469dd97c6c785dc426f4379fd29513c19667/tests/testthat/test-init.R#L27

**Comment by ankane** [comment]
Hey @kevinushey, thanks for reporting. Fixed in the commit above.
