### ISSUE TITLE
Get rid of the Install Jetpack to use a virtual environment for this project message

### ISSUE THREAD

**Issue by rockdeme** [ankane/jetpack#27]
Hi!

I had jetpack installed previously and even though it is uninstalled I still get the `Install Jetpack to use a virtual environment for this project` despite removing the files from my project directory. Can you help me with that? Thanks!

**Comment by ankane** [comment]
Hey @rockdeme, be sure to remove the Jetpack code from `.Rprofile` in your project directory.

```r
if (requireNamespace("jetpack", quietly=TRUE)) {
  jetpack::load()
} else {
  message("Install Jetpack to use a virtual environment for this project")
}
```

**Comment by rockdeme** [comment]
Thanks @ankane! It looks like there was another `.Rprofile` file in an unexpected place, deleted it and issue solved :)
